---
services:
  emqx:
  image: emqx/emqx
  ports:
    - 1883:1883
    - 18083:18083

  jaeger:
    image: jaegertracing/all-in-one:latest
    healthcheck:
      test: "/go/bin/all-in-one-linux status"
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - target: 4317
        published: 4317
        protocol: tcp
      - target: 16686
        published: 16686
        protocol: tcp
      - target: 14268
        published: 14268
        protocol: tcp
