apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-blackbox-exporter-config-map
data:
  emqx.config: |
    environment:
      EMQX_NAME: instance-1
      EMQX_LOADED_PLUGINS: "emqx_management,emqx_dashboard"
    ports:
      - 1883:1883
      - 18083:18083
  jeager.confg: |
    ports:
      - target: 6831
        published: 6831
        protocol: udp
      - target: 16686
        published: 16686
        protocol: tcp
      - target: 14268
        published: 14268
        protocol: tcp