---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mqtt-blackbox-exporter.fullname" . }}
  labels:
    {{- include "mqtt-blackbox-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    emqx:
      environment: {{- include .Values.emqx.environment }}
      ports: {{- include .Values.emqx.ports }}
    jeager:
      ports: {{- include .Values.jeager.ports }}