---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mqtt-blackbox-exporter.fullname" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "mqtt-blackbox-exporter.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- toYaml .Values.config | default "{}" | nindent 4 }}
